### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by murtyjones** [turnerlabs/terraform-ecs-fargate#27]
Thank you for this template. Looks great, especially the documentation!

I have a question about the [environment guide](https://github.com/turnerlabs/terraform-ecs-fargate/blob/master/README.md#envdev).

Say that you have a couple of environments, `production` and `dev` for example, and you want them to share a lot of the things in this template that currently live in `env/dev`. Is the idea for the user to move things into `base` as they become shared dependencies across environments?

**Comment by jritsema** [comment]
Hi @murtyjones, thanks for the feedback!  Yes, that is the idea.  Move any shared components up to the base directory.  Our philosophy is generally, the less you share the better, which makes each environment more isolated and portable.  That said, some folks here do share ALBs across environments so that might be an example of a shared component.
